{
  "services": {
    "devcontainer": {
      "command": "sh -exc 'while sleep 1m; do :; done'",
      "image": "public.ecr.aws/acilearning/haskell:9.6.1",
      "init": true,
      "volumes": [
        "..:/workspaces/weeder",
        "./volumes/cabal/cache:/home/vscode/.cache/cabal",
        "./volumes/cabal/state:/home/vscode/.local/state/cabal",
      ],
      "working_dir": "/workspaces/weeder"
    }
  }
}
